[project]
name = "event_processing"
description = "Tools for processing and visualizing event streams from NCNR instruments"
version = "0.0.1"
authors = [
    { name = "Paul Kienzle", email = "paul.kienzle@nist.gov" },
    { name = "Brian Maranville", email = "brian.maranville@nist.gov" }
]
dependencies = [
    "fastapi",
    "uvicorn",
    "h5py",
    "hdf5plugin",
    "msgpack",
    "numpy",
    "pydantic",
    "requests",
    "plotly",
    "nicegui",
    "kafka-python",
    "avroc",
    "pylru",
    "scipy",
    "numba",
    "psutil",
    "diskcache"
]

[project.scripts]
event-processing = "event_processing.rebinning_api.server:main"

[project.optional-dependencies]
dev = [
]
confluent = [
    "confluent-kafka"
]
torch = [
    "torch"
]

[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["event_processing*"]
exclude = ["event_processing.rebinning_client.quasar-project*"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"*" = ["*.pem"]
"event_processing.rebinning_client" = [
    "*.patch",
    "static/*",
    "web-client/*.json",
    "web-client/*.js",
    "web-client/*.cjs",
    "web-client/*.ts",
    "web-client/*.html",
    "web-client/.eslintignore",
    "web-client/public/**/*",
    "web-client/src/**/*",
    "web-client/dist/**/*",
]